# Generated by Django 2.2.7 on 2019-11-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repository',
            new_name='Repositories',
        ),
    ]
